export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_CURRENT_LESSON = "SET_CURRENT_LESSON";
export const LESSON_LOADING = "LESSON_LOADING";